# Generated by Django 5.2.12 on 2026-06-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='dob',
        ),
    ]
