# Generated by Django 6.0.2 on 2026-03-03 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_alter_enrollment_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
