# Generated by Django 5.2.12 on 2026-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_remove_enrollment_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_expiry_notif_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
