# Generated by Django 5.2.12 on 2026-04-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0003_delete_gallery_rename_reference_enrollment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('🎉', '🎉 Party / Offer'), ('💪', '💪 Training'), ('🏖️', '🏖️ Summer / Season'), ('⚡', '⚡ Alert / Closure'), ('🏷️', '🏷️ Deal / Discount'), ('📢', '📢 Announcement'), ('', 'No icon')], default='📢', max_length=5)),
                ('message', models.CharField(help_text='Short notification text (max 200 chars)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shows first')),
            ],
            options={
                'verbose_name': 'Gym Notification',
                'verbose_name_plural': 'Gym Notifications',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='attendence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
