# Generated by Django 5.2.12 on 2026-04-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0004_gymnotification_alter_attendence_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='face_samples',
        ),
    ]
