# Generated by Django 5.2.12 on 2026-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0004_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
