# Generated by Django 6.0.2 on 2026-03-03 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0004_alter_enrollment_duedate_alter_enrollment_doj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='gallery')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='unique_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
