# Generated by Django 6.0.2 on 2026-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0005_gallery_enrollment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='unique_id',
            field=models.CharField(db_index=True, editable=False, max_length=4, unique=True),
        ),
    ]
