# Generated by Django 5.2.12 on 2026-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0005_remove_enrollment_face_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
