# Generated by Django 5.2.12 on 2026-04-15 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0006_membershipplan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pendingAmount',
            field=models.DecimalField(
                default=0, max_digits=10, decimal_places=2),
        ),
    ]
