# Generated by Django 5.2.12 on 2026-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0007_enrollment_pendingamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pendingStatus',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pendingpaymentMethod',
            field=models.CharField(blank=True, choices=[('C', 'CASH'), ('U', 'UPI'), ('B', 'UPI + CASH')], max_length=1, null=True),
        ),
    ]
