# Generated by Django 5.2.12 on 2026-04-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0008_enrollment_pendingstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='pendingStatus',
        ),
    ]
