# Generated by Django 6.0.2 on 2026-03-04 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0008_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 4, 0, 41, 3, 39292, tzinfo=datetime.timezone.utc)),
        ),
    ]
