# Generated by Django 6.0.2 on 2026-03-04 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0009_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
