# Generated by Django 5.2.12 on 2026-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0009_remove_enrollment_pendingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paymentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
