# Generated by Django 5.2.12 on 2026-04-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0010_enrollment_paidamount_enrollment_paymentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pendingpaymentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
