# Generated by Django 6.0.2 on 2026-03-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0010_alter_attendence_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
