# Generated by Django 6.0.2 on 2026-03-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0013_attendence_date_alter_attendence_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
