# Generated by Django 6.0.2 on 2026-03-26 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0016_alter_attendence_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('user', 'date')},
        ),
    ]
