# Generated by Django 6.0.2 on 2026-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
