# Generated by Django 6.0.2 on 2026-02-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('phonenumber', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('doj', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('B', 'Basic'), ('P', 'Popular'), ('A', 'Annual')], default='B', max_length=1)),
                ('trainer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Reference', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
