# Generated by Django 6.0.2 on 2026-03-01 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='doj',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
