# Generated by Django 6.0.2 on 2026-03-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_alter_enrollment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='doj',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
