# Generated by Django 6.0.2 on 2026-03-02 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0003_alter_enrollment_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='plan',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='selectPlan',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trainer',
            field=models.CharField(max_length=100),
        ),
    ]
