# Generated by Django 6.0.2 on 2026-03-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0003_contact_timestamp_alter_enrollment_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
