# Generated by Django 6.0.2 on 2026-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0003_alter_enrollment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paymentStatus',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
