# Generated by Django 6.0.2 on 2026-03-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0004_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
