# Generated by Django 6.0.2 on 2026-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0005_rename_phonenumber_trainer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Amount',
            field=models.CharField(blank=True, choices=[('1', '500'), ('3', '1300'), ('6', '7999')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paymentStatus',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('P', 'Pending')], max_length=1, null=True),
        ),
    ]
