# Generated by Django 6.0.2 on 2026-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0006_rename_phonenumber_enrollment_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('C', 'CASH'), ('U', 'UPI'), ('B', 'UPI + CASH')], max_length=1, null=True),
        ),
    ]
