# Generated by Django 6.0.2 on 2026-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0006_alter_enrollment_phone_alter_enrollment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='doj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
