# Generated by Django 6.0.2 on 2026-03-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0007_enrollment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='plan',
            field=models.CharField(choices=[('B', 'Basic'), ('P', 'Popular'), ('A', 'Annual'), ('T', 'TRIAL')], default='B', max_length=1),
        ),
    ]
